packages:
  - '.'
extra-deps:
  - git: https://github.com/poor-a/ActiveHs-misc.git
    commit: 7f53c29f1a0b3e858ef0a8d238ecf5566c25606b
    subdirs:
      - data-pprint
      - dia-base
      - dia-functions
  - snap-1.1.1.0
  - heist-1.1
  - map-syntax-0.3
  - pwstore-fast-2.4.4
  - xmlhtml-0.2.5.2
resolver: lts-12.1
